# Generated by Django 2.0.2 on 2020-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_auto_20200505_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approve',
            field=models.BooleanField(default=True, verbose_name='表示する'),
        ),
    ]
