# Generated by Django 2.0.2 on 2020-05-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0004_auto_20200505_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approve',
            field=models.BooleanField(default=True, help_text='非公開にする場合はチェックを外してください', verbose_name='表示する'),
        ),
    ]
