# Generated by Django 2.0.2 on 2020-05-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0006_auto_20200505_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='primary_image',
            field=models.ImageField(default='defo', upload_to='images', verbose_name='トップ画像'),
        ),
    ]
