# Generated by Django 2.0.2 on 2020-05-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0007_info_primary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='primary_image',
            field=models.ImageField(default='images/image3_vONrbta.png', upload_to='images', verbose_name='トップ画像'),
        ),
    ]
