# Generated by Django 2.0.2 on 2020-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0008_auto_20200506_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='primary_image',
            field=models.ImageField(default='images/image3.png', upload_to='images', verbose_name='トップ画像'),
        ),
    ]
